/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_neuralsearch_sparse_common_NativeLibrary */

#ifndef _Included_org_opensearch_neuralsearch_sparse_common_NativeLibrary
#define _Included_org_opensearch_neuralsearch_sparse_common_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_neuralsearch_sparse_common_NativeLibrary
 * Method:    dp
 * Signature: ([S[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_neuralsearch_sparse_common_NativeLibrary_dp
  (JNIEnv *, jobject, jshortArray, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
