/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_neuralsearch_sparse_jni_NativeLibrary */

#ifndef _Included_org_opensearch_neuralsearch_sparse_jni_NativeLibrary
#define _Included_org_opensearch_neuralsearch_sparse_jni_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_neuralsearch_sparse_jni_NativeLibrary
 * Method:    dp
 * Signature: ([S[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_neuralsearch_sparse_jni_NativeLibrary_dp
  (JNIEnv *, jobject, jshortArray, jfloatArray, jfloatArray);

/*
 * Class:     org_opensearch_neuralsearch_sparse_jni_NativeLibrary
 * Method:    dp2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_neuralsearch_sparse_jni_NativeLibrary_dp2
  (JNIEnv *, jobject);

/*
 * Class:     org_opensearch_neuralsearch_sparse_jni_NativeLibrary
 * Method:    dp3
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_neuralsearch_sparse_jni_NativeLibrary_dp3
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     org_opensearch_neuralsearch_sparse_jni_NativeLibrary
 * Method:    dp4
 * Signature: (Ljava/nio/ByteBuffer;)F
 */
JNIEXPORT jfloat JNICALL Java_org_opensearch_neuralsearch_sparse_jni_NativeLibrary_dp4
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
