name: Clean Up Disk Space
description: Clean up disk space in CI environment

runs:
  using: composite
  steps:
    - name: Check initial disk space
      run: df -h
      shell: bash

    - name: Clean up disk space
      run: |
        # Remove temp files
        sudo rm -rf /__w/_temp || true
        sudo rm -rf /tmp/* || true
        
        # Clean apt cache
        sudo apt-get clean || true
        
        # Remove unnecessary packages
        sudo apt-get autoremove -y || true
        
        # Clean docker if available
        docker system prune -af || true
        
        # Remove large directories commonly found in CI
        sudo rm -rf /usr/share/dotnet || true
        sudo rm -rf /opt/ghc || true
        sudo rm -rf /usr/local/share/boost || true
      shell: bash

    - name: Check final disk space
      run: df -h
      shell: bash