name: Clean Up Disk Space
description: Clean up disk space in CI environment

runs:
  using: composite
  steps:
    - name: Check initial disk space
      run: df -h
      shell: bash

    - name: Clean up disk space
      run: |
        # Clean apt cache
        sudo apt-get clean || true
        
        # Remove unnecessary packages
        sudo apt-get autoremove -y || true
        
        # Clean docker if available
        docker system prune -af || true
        
        # Remove large directories commonly found in CI
        rm -rf /usr/share/dotnet || true
        rm -rf /opt/ghc || true
        rm -rf /usr/local/share/boost || true
        
        # Remove CodeQL
        rm -rf /__t/CodeQL || true
        
        # Remove Go
        rm -rf /__t/go || true
        
        # Remove GCC
        rm -rf /usr/libexec || true
      shell: bash

    - name: Check final disk space
      run: df -h
      shell: bash
